[package]
name = "zrpc-wallet-sdk"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
tokio.workspace = true
zrpc-client = { path = "../client" }
zrpc-payments = { path = "../payments" }
zrpc-protocol = { path = "../protocol" }
zrpc-transport = { path = "../transport" }
zrpc-verifier = { path = "../verifier" }
zrpc-wallet-read = { path = "../wallet-read" }
