[package]
name = "zrpc-wallet-read"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
prost.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
zrpc-protocol = { path = "../protocol" }

[build-dependencies]
tonic-prost-build.workspace = true
